### ISSUE TITLE
is-empty to support jQuery objects.

### ISSUE THREAD

**Issue by jdalton** [AmpersandJS/amp#45]
Duck-typing `splice` with `length` is what dev tools in Chrome, Firebug, WebKit do and because of that libs like jQuery and MooTools have it as well. So by supporting that in `is-empty` you get support for more than just jQuery too.

**Comment by HenrikJoreteg** [comment]
I'm not convinced we should try to support these types of uses, will close, if someone using it want this functionality, please re-open this ticket.
