### ISSUE TITLE
expand trim regexp

### ISSUE THREAD

**Issue by jdalton** [AmpersandJS/amp#48]
The `amp-trim` regexp uses `\s` which differs from engine to engine on what whitespace is matched. It's better to be explicit in this case or you get into similar situations as the native trim use.

**Comment by HenrikJoreteg** [comment]
now using trim from jquery

**Comment by jdalton** [comment]
Right, though this is a common form I think it's better to be explicit with whitespace matched and avoid the `\s` character class as it's historically had [issues with whitespace consistency](http://perfectionkills.com/whitespace-deviations/) and leaves wiggle room for what is considered whitespace in the future.

**Comment by HenrikJoreteg** [comment]
Feel free to suggest an specific alternative.

**Comment by jdalton** [comment]
Something like [es5-shim](https://github.com/es-shims/es5-shim/blob/c043a30047e5c2754bfba85f9d30e5084a24f2b8/es5-shim.js#L1396-L1415).
