### ISSUE TITLE
Cannot find module 'uglifyjs'

### ISSUE THREAD

**Issue by TimothyRHuertas** [AmpersandJS/amp#82]
I get "Error: Cannot find module 'uglifyjs'" when I run npm install.  I am a new00be at npm, but it looks as if the module may be unpublished https://registry.npmjs.org/uglifyjs

Thoughts

**Comment by fyockm** [comment]
@TimothyRHuertas you can get up and running by just removing the `uglifyjs` line from `amp/package.json` and re-run `npm install` again.

From what I can see, `uglifyjs` is only used in the size calculation.

**Comment by jrunning** [comment]
@fyockm After removing `uglifyjs` from `package.json`, `npm install` still fails because `js-size` also depends on `uglifyjs`.

**Comment by TimothyRHuertas** [comment]
I am impressed with the build scheme ampersandjs uses.  To better understand it I want to add a module.  @fyockm event though npm install still fails (as @fyockm pointed out), your suggestion will unblock me for now.

**Comment by fyockm** [comment]
@jrunning sorry, I just tried and found the same. Working on a PR for `js-size` and `amp` to remove that dependency.
